[package]
name = "fly-cheap"
version = "0.1.0"
authors = ["Florin Lipan <florinlipan@gmail.com>"]

[lib]
doctest = false

[features]
default = ["mockito/use_hyper"]

[dependencies]
toml = "0.1.25"
rustc-serialize = "0.3.16"
hyper = "0.7.2"
regex = "0.1.47"
rusqlite = "0.6.0"
mockito = "0.1.4"
